# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: tests/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          - "-l"
          - "80"
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
