[tool.poetry]
name = "python-scratch"
version = "0.0.1"
description = "Playground for learning python."
authors = ["Matt Pladna <pladdypants@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.7"

[tool.poetry.dev-dependencies]
dis = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
